id: P2444632A
initial_creation_type: input
source_metadata:
  title: Works of Gatön Ngawang Legpa
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    0d07:
      title: སྒ་སྟོན་རྡོ་རྗེ་འཆང་འཇམ་མགོན་ངག་དབང་ལེགས་པའི་གསུང་ཐོར་བུ་ཁག
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 0d07.txt
      order: 1
    5cdd:
      title: ཀ་མད་སུམ་ཅུ་ལས་དྲས་པའི་དབྱངས་སུ་བསྡེབས་ནས་བྲིས་པ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 5cdd.txt
      order: 2
    75ca:
      title: བླ་མ་རིན་ཆེན་འབྱུང་ལྡན་གྱི་རྣལ་འབྱོར་ཉམས་སུ་ལེན་ཚུལ་སྲིད་ཞིའི་དཔལ་འབྱོར་རབ་རྒྱས་དང་།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 75ca.txt
      order: 3
    c904:
      title: འཇམ་དབྱངས་བླ་མའི་རྣལ་འབྱོར་ཉམས་སུ་ལེན་ཚུལ་བྱིན་རླབས་ཆར་འབེབས།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: c904.txt
      order: 4
    ac81:
      title: འཇམ་དབྱངས་བླ་མ་ས་སྐྱ་པཎྜི་ཏ་ཁྱེད་ཐུགས་དགྱེས་པའི་ཕྲིན་ལས།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: ac81.txt
      order: 5
    6ff3:
      title: བླ་མ་རྡོ་རྗེ་འཆང་གི་རྣལ་འབྱོར་སྙིང་གི་བདུད་རྩི།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 6ff3.txt
      order: 6
    07fe:
      title: བདག་ཉིད་ཆེན་པོ་གཞུང་ལུགས་རབ་འབྱམས་པའི་བླ་མའི་རྣལ་འབྱོར་བྱིན་རླབས་ཆར་འདེབས།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 07fe.txt
      order: 7
    85e2:
      title: ལམ་ཟབ་ནང་གི་བླ་མའི་རྣལ་འབྱོར།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 85e2.txt
      order: 8
    57e9:
      title: བིརྺ་པའི་སྲུང་བའི་མན་ངག་བར་ཆད་ཀུན་སེལ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 57e9.txt
      order: 9
    9f10:
      title: ལམ་ཟབ་ཚར་གསུམ་ཁུག་པ་རྒྱུན་ཁྱེར།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 9f10.txt
      order: 10
    d03f:
      title: ཀྱཻ་རྡོར་ལམ་དུས་མ་ནོར་དོན་གསལ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: d03f.txt
      order: 11
    5fc2:
      title: འཁོར་འདས་དབྱེར་མེད་ཀྱི་ལྟ་བའི་སྙིང་པོ་བསྡུས་པ་སྐལ་བཟང་སྙིང་གི་བདུད་རྩི།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 5fc2.txt
      order: 12
    f01e:
      title: དག་པ་དྲན་པའི་འགྲེལ་པ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: f01e.txt
      order: 13
    8b92:
      title: རྗེ་བཙུན་བླ་མ་དམ་པ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 8b92.txt
      order: 14
    ab8f:
      title: རང་བཞིན་བརྒྱད་ཅུའི་རྟོག་པ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: ab8f.txt
      order: 15
    2c9a:
      title: མར་མེའི་སྨོན་ལམ་མཆོད་སྤྲིན་རྒྱ་མཚོ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 2c9a.txt
      order: 16
    29ba:
      title: གནོད་བྱེད་འབྱུང་པོའི་གསུར་བསྔོ་རྐྱེན་ངན་ཀུན་གྲོལ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 29ba.txt
      order: 17
    82e7:
      title: བྱང་ཆུབ་སེམས་དཔའི་སྨོན་ལམ་ཐེག་ཆེན་ལམ་གྱི་སྙིང་པོ།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: 82e7.txt
      order: 18
    a360:
      title: རྗེ་བླ་མ་ཀུན་དགའ་ཆོས་ལྷའི་རྣམ་ཐར།
      author: སྒ་སྟོན་ངག་དབང་ལེགས་པ།
      base_file: a360.txt
      order: 19
created_at: '2022-04-06T17:09:40.130853'
last_modified_at: '2022-04-06T17:09:40.130866'
